import fs from 'node:fs/promises';import crypto from 'node:crypto';import * as T from '../outputs/source/three.mjs';import {buildGT01Console} from '../outputs/source/center-console.mjs';
const a=buildGT01Console(T),{root,parts,definition}=a,revision=definition.revision.toLowerCase().replace('console-','');root.updateMatrixWorld(true);
let triangles=0;const missing=[],bad=[],ids=new Set();for(const p of parts){ids.add(p.userData.id);for(const k of ['id','referencePart','subPart','reference','purpose','receiving','orientation','authorDimensions','physicalBoundary','material','shapeSource'])if(!p.userData[k])missing.push([p.name,k]);for(const n of p.geometry.attributes.position.array)if(!Number.isFinite(n))bad.push(p.userData.id);triangles+=(p.geometry.index?.count||p.geometry.attributes.position.count)/3;await fs.access(new URL('../outputs/'+p.userData.reference,import.meta.url));}
const ray=new T.Raycaster();for(const p of parts)p.material.side=T.DoubleSide;
function hits(origin,direction,subset=parts,far=1000){ray.set(new T.Vector3(...origin),new T.Vector3(...direction));ray.far=far;return ray.intersectObjects(subset,false).map(h=>({id:h.object.userData.id,subPart:h.object.userData.subPart,point:h.point.toArray(),distance:h.distance}));}
const cavities=[-43,43].map(y=>({name:'cup '+y,probe:[43,y,456],hits:hits([43,y,456],[0,0,-1])}));
root.getObjectByName('I03-armrest-hinge').rotation.y=.96;root.updateMatrixWorld(true);cavities.push({name:'storage with lid open',probe:[270,0,500],hits:hits([270,0,500],[0,0,-1])});root.getObjectByName('I03-armrest-hinge').rotation.y=0;root.updateMatrixWorld(true);
const layers=[];for(const x of [-240,0,430])for(const z of [333,380,430]){const intervals=[];for(const sub of ['I03-P03','I03-P02','I03-P01']){const hs=hits([x,200,z],[0,-1,0],parts.filter(p=>p.userData.subPart===sub),200);intervals.push({sub,near:hs[0]?.point[1],far:hs.at(-1)?.point[1]});}layers.push({x,z,intervals,pass:intervals.every(v=>v.near>v.far)&&intervals.slice(1).every((v,i)=>intervals[i].far-v.near>=.18)});}
const shafts=[];for(const y of [-42,42]){const axis=new T.Vector3(-Math.sin(.12),0,Math.cos(.12)),p=new T.Vector3(-5,y,0).applyAxisAngle(new T.Vector3(0,1,0),-.12).add(new T.Vector3(-154,0,476)),origin=p.clone().addScaledVector(axis,-15);shafts.push({y,boreHits:hits(origin.toArray(),axis.toArray(),parts.filter(p=>['I03-P07','I03-P09'].includes(p.userData.subPart)),30)});}
const trim=parts.find(p=>p.userData.subPart==='I03-P08');const trimOpening=hits([-154,0,540],[0,0,-1],[trim],100);
const liningClearances=[];for(const z of [380,410,440,449]){const outer=hits([270,180,z],[0,-1,0],parts.filter(p=>p.userData.subPart==='I03-P14'),180),inner=hits([270,180,z],[0,-1,0],parts.filter(p=>p.userData.subPart==='I03-P15'),180);if(outer.length&&inner.length)liningClearances.push({kind:'storage',z,gapMm:outer.at(-1).point[1]-inner[0].point[1]});}
for(const y of [-43,43])for(const z of [390,415,427,439])for(let i=0;i<6;i++){const angle=i*Math.PI/3,dir=[-Math.cos(angle),-Math.sin(angle),0],o=[43+100*Math.cos(angle),y+100*Math.sin(angle),z],outer=hits(o,dir,parts.filter(p=>p.userData.subPart==='I03-P12'),100),inner=hits(o,dir,parts.filter(p=>p.userData.subPart==='I03-P13'),100);if(outer.length&&inner.length)liningClearances.push({kind:'cup',y,z,angle,gapMm:inner[0].distance-outer.at(-1).distance});}
const box=new T.Box3().setFromObject(root);const report={revision:definition.revision,sourceSHA256:crypto.createHash('sha256').update(await fs.readFile(new URL('../outputs/source/center-console.mjs',import.meta.url))).digest('hex'),meshes:parts.length,triangles,uniqueIds:ids.size===parts.length,missing,nonFinite:bad,bounds:{min:box.min.toArray(),max:box.max.toArray()},cavities,layers,shafts,trimOpening,definition,parts:parts.map(p=>({name:p.name,...p.userData}))};
report.liningClearances=liningClearances;
report.checksPass=ids.size===parts.length&&!missing.length&&!bad.length&&layers.every(p=>p.pass)&&cavities.every(c=>c.hits[0]?.point[2]<400)&&shafts.every(p=>!p.boreHits.length)&&!trimOpening.length&&definition.envelope.main.min[0]>=-338&&definition.envelope.main.max[0]<=542&&definition.envelope.main.max[1]<=119&&definition.envelope.main.max[2]<=473;
report.checksPass=report.checksPass&&liningClearances.length>0&&liningClearances.every(p=>p.gapMm>=0)&&cavities.every(c=>c.hits[0]?.subPart===(c.name.startsWith('cup')?'I03-P13':'I03-P15'));
await fs.writeFile(new URL('../outputs/quality/console-native-'+revision+'.json',import.meta.url),JSON.stringify(report,null,2));console.log(JSON.stringify({checksPass:report.checksPass,bounds:report.bounds,meshes:report.meshes,triangles,cavities:cavities.map(c=>({name:c.name,first:c.hits[0]})),layersPass:layers.every(p=>p.pass),shafts,trimOpening}));if(!report.checksPass)process.exitCode=1;
