import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import crypto from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire('LOCAL_PATH_OMITTED'),{chromium}=require('playwright');
const base=path.resolve(import.meta.dirname,'..'),dir=path.join(base,'outputs/quality'),run=process.argv[2]||'r1';if(!/^r\d+$/.test(run))throw Error('run');
const sha=async()=>crypto.createHash('sha256').update(await fs.readFile(path.join(base,'outputs/source/center-console.mjs'))).digest('hex');
const log={run,ownerPid:process.pid,startedAt:new Date().toISOString(),sourceSHA256:await sha(),errors:[],frames:[]};
const server=http.createServer(async(req,res)=>{try{const p=path.resolve(base,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(base+path.sep))throw Error('scope');res.setHeader('Content-Type',p.endsWith('.html')?'text/html':p.endsWith('.mjs')?'text/javascript':p.endsWith('.png')?'image/png':'application/octet-stream');res.end(await fs.readFile(p));}catch{res.writeHead(404).end();}});let native,browser;
try{await new Promise(r=>server.listen(0,'127.0.0.1',r));log.port=server.address().port;native=await chromium.launchServer({channel:'chrome',headless:true});log.browserPid=native.process().pid;browser=await chromium.connect(native.wsEndpoint());const page=await browser.newPage({viewport:{width:1600,height:930},deviceScaleFactor:1});page.on('pageerror',e=>log.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')log.errors.push(m.text());});await page.goto('http://127.0.0.1:'+log.port+'/outputs/quality/console-assembly.html');await page.waitForFunction(()=>window.CONSOLE,{timeout:45000});
async function snap(name,full=false){const file=`console-${run}-${name}.png`;await fs.writeFile(path.join(dir,file),await page.locator(full?'body':'#stage').screenshot());log.frames.push({file,state:await page.evaluate(()=>CONSOLE.state())});}
for(const v of ['iso','front','rear','side','driver','top','bottom','control-close','hinge-close']){await page.evaluate(v=>CONSOLE.view(v),v);await snap(v,v==='iso');}
await page.evaluate(()=>{CONSOLE.lid(true);CONSOLE.view('storage-close');});await snap('open-storage');await page.evaluate(()=>{CONSOLE.lid(false);CONSOLE.layers('exploded');CONSOLE.view('iso');});await snap('layered');
if(process.argv.includes('--parts')){const ids=await page.evaluate(()=>[...new Set(CONSOLE.assembly.parts.map(p=>p.userData.subPart))].map(subPart=>({subPart,id:CONSOLE.assembly.parts.find(p=>p.userData.subPart===subPart).userData.id})));for(const item of ids){await page.evaluate(id=>{CONSOLE.layers('assembled');CONSOLE.select(id);CONSOLE.view('iso');},item.id);await page.locator('#partRef').evaluate(img=>img.decode());await snap(item.subPart,true);}}
for(const sub of ['I03-P11','I03-P14','I03-P16','I03-P18']){await page.evaluate(sub=>{CONSOLE.layers('assembled');CONSOLE.select(CONSOLE.assembly.parts.find(p=>p.userData.subPart===sub).userData.id);CONSOLE.view('bottom');},sub);await snap(sub+'-underside');}
await page.evaluate(()=>{CONSOLE.select('all');CONSOLE.layers('assembled');CONSOLE.view('iso');});const before=await page.evaluate(()=>CONSOLE.state().camera);await page.mouse.move(500,400);await page.mouse.down();await page.mouse.move(600,440,{steps:4});await page.mouse.up();const after=await page.evaluate(()=>CONSOLE.state().camera);log.interaction={dragChangesCamera:JSON.stringify(before)!==JSON.stringify(after)};await page.locator('#exploded').click();log.interaction.layerButton=await page.evaluate(()=>CONSOLE.state().mode==='exploded');await page.locator('#assembled').click();log.interaction.assemblyButton=await page.evaluate(()=>CONSOLE.state().mode==='assembled');await page.locator('#lid').click();log.interaction.lidButton=await page.evaluate(()=>CONSOLE.state().lidAngle>0);await page.evaluate(()=>CONSOLE.lid(false));
if(process.argv.includes('--context')){log.contextSourceSHA256=crypto.createHash('sha256').update(await fs.readFile(path.join(base,'outputs/source/vehicle.mjs'))).digest('hex');await page.evaluate(()=>CONSOLE.context());await snap('reinstalled',true);log.contextRevision=await page.evaluate(()=>CONSOLE.contextRevision);log.contextAnalysis=await page.evaluate(()=>CONSOLE.contextAnalysis);}
log.complete=!log.errors.length;
}catch(e){log.failure=e.stack;process.exitCode=1;}finally{if(browser)await browser.close();if(native){await native.close();log.browserExited=native.process().exitCode!==null;}await new Promise(r=>server.close(r));log.serverClosed=!server.listening;log.bindingsUnchanged=log.sourceSHA256===await sha();log.finishedAt=new Date().toISOString();await fs.writeFile(path.join(dir,`console-browser-${run}.json`),JSON.stringify(log,null,2));console.log(JSON.stringify({complete:log.complete,frames:log.frames.length,errors:log.errors,failure:log.failure,browserPid:log.browserPid,port:log.port,browserExited:log.browserExited,serverClosed:log.serverClosed,bindingsUnchanged:log.bindingsUnchanged}));}
