import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {buildModel} from '../outputs/source/model.mjs';
import * as T from '../outputs/source/three.mjs';
const raw=await fs.readFile('outputs/source/rim-preserved.js','utf8');
const rim=JSON.parse(raw.slice(raw.indexOf('=')+1).trim().replace(/;$/,''));
const model=buildModel(rim);model.root.updateMatrixWorld(true);
const parts=model.parts.map(p=>{let vertices=0,triangles=0,invalid=0;p.traverse(o=>{if(!o.isMesh)return;const a=o.geometry.attributes.position;vertices+=a.count;triangles+=(o.geometry.index?.count||a.count)/3;for(const v of a.array)if(!Number.isFinite(v))invalid++;});const b=new T.Box3().setFromObject(p);return {id:p.name,name:p.userData.name,system:p.userData.system,reference:p.userData.reference,provenance:p.userData.provenance,vertices,triangles,invalid,bounds:[b.min.toArray(),b.max.toArray()]};});
function inside(p,poly){let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])c=!c;}return c;}
const rimSection=rim.barrel_section_r_z,tire=model.parts.find(p=>p.name==='W02').children[0].geometry.attributes.position;
const penetrations=[];for(let j=0;j<tire.count;j++){const x=tire.getX(j),y=tire.getY(j);if(Math.abs(y)>1e-5||x<0)continue;const p=[Math.hypot(x,y),tire.getZ(j)];if(inside(p,rimSection))penetrations.push(p);}
const rotor=model.parts.find(p=>p.name==='B01'),hub=model.parts.find(p=>p.name==='H01');const rb0=new T.Box3().setFromObject(rotor.children[0]),rb1=new T.Box3().setFromObject(rotor.children[1]),pilot=new T.Box3().setFromObject(hub.children[1]);
const report={revision:model.root.userData.revision,sourceRimSHA256:crypto.createHash('sha256').update(raw).digest('hex'),parts,relations:{preservedRimSource:crypto.createHash('sha256').update(raw).digest('hex')==='f7bb3167d4911bfa543dd2f1a76d6cb45e808ff9d76a2146fae1539180402740',finiteGeometry:parts.every(p=>p.invalid===0),ballCount:parts.filter(p=>p.id.startsWith('H04-')).length,innerRaces:parts.filter(p=>/^H03/.test(p.id)).length,pistons:parts.filter(p=>/^B06/.test(p.id)).length,pressureSeals:parts.filter(p=>/^B10/.test(p.id)).length,dustBoots:parts.filter(p=>/^B11/.test(p.id)).length,rotorFrictionAxialGap:rb1.min.z-rb0.max.z,pilotDiametralClearance:rim.dimensions_mm.center_bore-(pilot.max.x-pilot.min.x),tireRimMeridionalSampleInside:penetrations},scope:'Construction checks only; no full 3D interference or manufacturing claim',wholeCarComplete:false};
await fs.writeFile('outputs/source/geometry-readback.json',JSON.stringify(report,null,2));console.log(JSON.stringify({partCount:parts.length,...report.relations}));
const profile=[];for(let i=0;i<tire.count;i++){if(Math.abs(tire.getY(i))>1e-5)break;profile.push([tire.getZ(i),-tire.getX(i)]);}
const poly=ps=>'M'+ps.map(p=>p.join(',')).join('L')+'Z';
const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1500" height="680" viewBox="0 0 1500 680"><rect width="1500" height="680" fill="#f4f3ee"/><g font-family="Arial, sans-serif" fill="#24332d"><text x="55" y="50" font-size="25">GT-01 / R3 — TIRE–RIM MERIDIONAL SECTION</text><text x="55" y="83" font-size="16">Actual new tire mesh at theta = 0; preserved rim barrel profile. Visual reconstruction, not manufacturing dimensions.</text></g><g transform="translate(750 160) scale(4.7)"><g transform="translate(0 305)"><path d="${poly(profile)}" fill="#323d40" stroke="#182123" stroke-width=".25"/><path d="${poly(rimSection.map(([r,z])=>[z,-r]))}" fill="#cc9e5b" stroke="#73552c" stroke-width=".3"/></g></g><g font-family="Arial, sans-serif" fill="#24332d" font-size="17"><text x="55" y="598">Charcoal: independently reconstructed tire / Gold: preserved rim barrel</text><text x="55" y="630">Front and rear bead returns follow the same source barrel; this section does not certify full 3D clearance.</text></g></svg>`;
await fs.writeFile('outputs/views/tire-seat.svg',svg);
